# Generated by Django 4.2.24 on 2025-10-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_remove_restaurant_current_open_now_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantphoto',
            options={'ordering': ['-collected_at', 'id'], 'verbose_name': '餐廳圖片', 'verbose_name_plural': '餐廳圖片'},
        ),
        migrations.AlterField(
            model_name='restaurantphoto',
            name='remote_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='遠端圖片 URL'),
        ),
        migrations.AddIndex(
            model_name='restaurantphoto',
            index=models.Index(fields=['restaurant', 'source'], name='restaurants_restaur_945fde_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantphoto',
            index=models.Index(fields=['remote_url'], name='restaurants_remote__98fc01_idx'),
        ),
        migrations.AddConstraint(
            model_name='restaurantphoto',
            constraint=models.UniqueConstraint(condition=models.Q(('remote_url__isnull', False), models.Q(('remote_url', ''), _negated=True)), fields=('restaurant', 'remote_url'), name='uniq_photo_remote_url_per_restaurant'),
        ),
        migrations.AddConstraint(
            model_name='restaurantphoto',
            constraint=models.UniqueConstraint(condition=models.Q(('photo_reference__isnull', False), models.Q(('photo_reference', ''), _negated=True)), fields=('restaurant', 'photo_reference'), name='uniq_photo_reference_per_restaurant'),
        ),
    ]
